### ISSUE TITLE
Store APIs using gob instead of JSON

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-cli#14]
BoltDB objects are currently stored as marshalled JSON objects. In future it may be simpler to store these using [the gob encoding package](https://golang.org/pkg/encoding/gob/) in Go.

**Comment by mvdan** [comment]
There *is* a problem I forgot to mention with Gobs. They are not backwards nor forwards compatible, so they're not good for persistent storage. For example, if we add a field to a struct, the data may break because Gob uses "field numbers" (indexes to fields) instead of their full names.

It's a double-edged sword; it's much faster and handles many more Go types since it's fine-tuned for Go usage. But on the other hand it assumes that the data structure doesn't change.

There are fancier wire formats that are faster/smaller than JSON but also handle compatibility, such as Protobuf. But then you're getting into quite a lot of added complexity.

Unless performance is a priority (are we going to store thousands of APIs?) or JSON limits us in some way, I'd just stick to JSON. Apologies for suggesting this in the first place; I forgot about the gob gotcha.

**Comment by kohrVid** [comment]
@mvdan, no worries. Thanks for the updated advice.
